/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Config.Koneksi;
import Controller.RuanganController;
import Controller.SarprasController;
import Model.Ruangan;
import Model.Sarpras;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

public class MainApp extends javax.swing.JFrame {
    DefaultTableModel tbl;
    Connection con;
    Koneksi konek;
    Statement st;
    ResultSet rs;

    private void showEditForm(){
                content.removeAll();
                content.repaint();
                content.revalidate();
        
                content.add(formEditSrp);
                content.repaint();
                content.revalidate();
    }
    private void showEditFormRR(){
                content.removeAll();
                content.repaint();
                content.revalidate();
        
                content.add(editHapusPanel);
                content.repaint();
                content.revalidate();
    }
    private void indexRuangan(){
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(ruanganPanel);
        content.repaint();
        content.revalidate();
        table_ruangan();
    }
    private void Clear(){
        txt_kdSarpras.setText(null);
        txt_nm_sarpras.setText(null);
        txt_jumlah_sarpras.setText(null);
        txt_kondisi_sarpras.setSelectedIndex(0);
        txt_jenis_sarpras.setSelectedIndex(0);
    }
    void table_sarpras(){
    Object[] col = {"Kode Sarpras","Nama sarpras","Jumlah","Kondisi","Jenis"};
        tbl = new DefaultTableModel(null,col);
        DefaultTableModel model = tbl;
        Sarpras sr = new SarprasController();
        sr.GetAll(tbl);
        tbl_sarpras.setModel(model);
    }
    void table_ruangan(){
    Object[] col = {"Kode Ruangan","Nama Ruangan","Jumlah","Kondisi"};
        tbl = new DefaultTableModel(null,col);
        DefaultTableModel model = tbl;
        Ruangan sr = new RuanganController();
        sr.GetAll(tbl);
        tbl_ruangan.setModel(model);
    }
    void formSarpras(){
        
        konek = new Koneksi();
        con = konek.getConnection();
        try{
            int row = tbl_sarpras.getSelectedRow();
            String klik_tbl = (tbl_sarpras.getModel().getValueAt(row, 0).toString());
            String query = "SELECT * FROM sarana WHERE kd_srp='"+klik_tbl+"'";
            st = con.createStatement();
            rs=st.executeQuery(query);
            if(rs.next()){
                showEditForm();
                String kode = rs.getString("kd_srp");
                kdSarpras.setText(kode);
                String nm = rs.getString("nama_srp");
                nm_sarpras.setText(nm);
                String jmlh = rs.getString("jumlah");
                jumlah_sarpras.setText(jmlh);
                String kondisis = rs.getString("kondisi");
                kondisi_sarpras.setSelectedItem(kondisis);
                String jenis = rs.getString("jenis");
                jenis_sarpras.setSelectedItem(jenis);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e );
        }
    }
     void formRuangan(){
        
        konek = new Koneksi();
        con = konek.getConnection();
        try{
            int row = tbl_ruangan.getSelectedRow();
            String klik_tbl = (tbl_ruangan.getModel().getValueAt(row, 0).toString());
            String query = "SELECT * FROM ruangan WHERE kode_ruangan='"+klik_tbl+"'";
            st = con.createStatement();
            rs=st.executeQuery(query);
            if(rs.next()){
                showEditFormRR();
                String kode = rs.getString("kode_ruangan");
                kd_ruangan.setText(kode);
                String nm = rs.getString("nama_ruangan");
                nm_ruangan.setText(nm);
                String jmlh = rs.getString("jumlah");
                jumlah.setText(jmlh);
                String kondisis = rs.getString("kondisi");
                kondisi.setSelectedItem(kondisis);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e );
        }
    }
    
    public MainApp() {
        setUndecorated(true);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSarpras = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRuangan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        session = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        dashboarPanel = new javax.swing.JPanel();
        welcomeText = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ruanganPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ruangan = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        formruangan = new javax.swing.JPanel();
        form_add = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_kd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_kondisi = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        editHapusPanel = new javax.swing.JPanel();
        form_edit = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        kd_ruangan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        nm_ruangan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        kondisi = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        sarprasPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnAdd_sarpras = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_sarpras = new javax.swing.JTable();
        add_sarpras = new javax.swing.JPanel();
        form_add_srp = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txt_kdSarpras = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_nm_sarpras = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txt_jumlah_sarpras = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txt_kondisi_sarpras = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        btnSimpanSrp = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txt_jenis_sarpras = new javax.swing.JComboBox<>();
        formEditSrp = new javax.swing.JPanel();
        form_edit_srp = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        kdSarpras = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        nm_sarpras = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jumlah_sarpras = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        kondisi_sarpras = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        btnEditSrp = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jenis_sarpras = new javax.swing.JComboBox<>();
        btnHpsSrp = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jPanel1.setBackground(new java.awt.Color(235, 234, 232));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 239, 226), 1, true));

        sidebar.setBackground(new java.awt.Color(10, 157, 194));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logolight.png"))); // NOI18N

        btnHome.setBackground(new java.awt.Color(10, 157, 194));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dashboard2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSarpras.setBackground(new java.awt.Color(10, 157, 194));
        btnSarpras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSarprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSarprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSarprasMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sarpras.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sarpras");

        javax.swing.GroupLayout btnSarprasLayout = new javax.swing.GroupLayout(btnSarpras);
        btnSarpras.setLayout(btnSarprasLayout);
        btnSarprasLayout.setHorizontalGroup(
            btnSarprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSarprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSarprasLayout.setVerticalGroup(
            btnSarprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSarprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSarprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnRuangan.setBackground(new java.awt.Color(10, 157, 194));
        btnRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRuanganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRuanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRuanganMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ruangan.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data Ruangan");

        javax.swing.GroupLayout btnRuanganLayout = new javax.swing.GroupLayout(btnRuangan);
        btnRuangan.setLayout(btnRuanganLayout);
        btnRuanganLayout.setHorizontalGroup(
            btnRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRuanganLayout.setVerticalGroup(
            btnRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnLogout.setBackground(new java.awt.Color(10, 157, 194));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Logout");

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSarpras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRuangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(40, 40, 40)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        navbar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/session1.png"))); // NOI18N

        session.setBackground(new java.awt.Color(255, 255, 255));
        session.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        session.setText("Admin");

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(session, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setLayout(new java.awt.CardLayout());

        welcomeText.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("SELAMAT DATANG DI INVENTARIS SARANA & PRASARANA !");

        javax.swing.GroupLayout welcomeTextLayout = new javax.swing.GroupLayout(welcomeText);
        welcomeText.setLayout(welcomeTextLayout);
        welcomeTextLayout.setHorizontalGroup(
            welcomeTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        welcomeTextLayout.setVerticalGroup(
            welcomeTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeTextLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(30, 194, 235));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel10)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
        );

        jPanel5.setBackground(new java.awt.Color(30, 194, 235));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sarpras");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel6.setBackground(new java.awt.Color(30, 194, 235));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Dashboard");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel13)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
        );

        javax.swing.GroupLayout dashboarPanelLayout = new javax.swing.GroupLayout(dashboarPanel);
        dashboarPanel.setLayout(dashboarPanelLayout);
        dashboarPanelLayout.setHorizontalGroup(
            dashboarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboarPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(dashboarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboarPanelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        dashboarPanelLayout.setVerticalGroup(
            dashboarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboarPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(dashboarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        content.add(dashboarPanel, "card2");

        tbl_ruangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ruangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ruanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ruangan);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Data Ruangan");

        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tambah");
        btnAdd.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        btnAdd.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout ruanganPanelLayout = new javax.swing.GroupLayout(ruanganPanel);
        ruanganPanel.setLayout(ruanganPanelLayout);
        ruanganPanelLayout.setHorizontalGroup(
            ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ruanganPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(265, 265, 265))
            .addGroup(ruanganPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ruanganPanelLayout.setVerticalGroup(
            ruanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ruanganPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.add(ruanganPanel, "card3");

        form_add.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Data Ruangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("Kode ruangan");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Nama ruangan");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("Jumlah");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("Kondisi");

        txt_kondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kondisi ....", "Bagus", "Sedang diperbaiki", "Rusak" }));

        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" Simpan");
        btnSimpan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        btnSimpan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        javax.swing.GroupLayout form_addLayout = new javax.swing.GroupLayout(form_add);
        form_add.setLayout(form_addLayout);
        form_addLayout.setHorizontalGroup(
            form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_addLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(38, 38, 38)
                .addGroup(form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_kd)
                    .addComponent(txt_nama)
                    .addComponent(txt_jumlah)
                    .addComponent(txt_kondisi, 0, 163, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_addLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        form_addLayout.setVerticalGroup(
            form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_addLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout formruanganLayout = new javax.swing.GroupLayout(formruangan);
        formruangan.setLayout(formruanganLayout);
        formruanganLayout.setHorizontalGroup(
            formruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formruanganLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(form_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        formruanganLayout.setVerticalGroup(
            formruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formruanganLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(form_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        content.add(formruangan, "card4");

        form_edit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Data Ruangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setText("Kode ruangan");

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel25.setText("Nama ruangan");

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel26.setText("Jumlah");

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel27.setText("Kondisi");

        kondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kondisi ....", "Bagus", "Sedang diperbaiki", "rusak" }));

        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Hapus");
        btnHapus.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hapus.png"))); // NOI18N
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(" Edit");
        btnEdit.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout form_editLayout = new javax.swing.GroupLayout(form_edit);
        form_edit.setLayout(form_editLayout);
        form_editLayout.setHorizontalGroup(
            form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_editLayout.createSequentialGroup()
                .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(form_editLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(38, 38, 38)
                        .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kd_ruangan)
                            .addComponent(nm_ruangan)
                            .addComponent(jumlah)
                            .addComponent(kondisi, 0, 163, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, form_editLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        form_editLayout.setVerticalGroup(
            form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_editLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd_ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(nm_ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(form_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout editHapusPanelLayout = new javax.swing.GroupLayout(editHapusPanel);
        editHapusPanel.setLayout(editHapusPanelLayout);
        editHapusPanelLayout.setHorizontalGroup(
            editHapusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editHapusPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(form_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        editHapusPanelLayout.setVerticalGroup(
            editHapusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editHapusPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(form_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        content.add(editHapusPanel, "card5");

        sarprasPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sarprasPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                sarprasPanelComponentShown(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel23.setText("Data Sarana");

        btnAdd_sarpras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd_sarpras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd_sarprasMouseClicked(evt);
            }
        });
        btnAdd_sarpras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Tambah");
        btnAdd_sarpras.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        btnAdd_sarpras.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbl_sarpras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sarpras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sarprasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_sarpras);

        javax.swing.GroupLayout sarprasPanelLayout = new javax.swing.GroupLayout(sarprasPanel);
        sarprasPanel.setLayout(sarprasPanelLayout);
        sarprasPanelLayout.setHorizontalGroup(
            sarprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sarprasPanelLayout.createSequentialGroup()
                .addGroup(sarprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sarprasPanelLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel23))
                    .addGroup(sarprasPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAdd_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(sarprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sarprasPanelLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        sarprasPanelLayout.setVerticalGroup(
            sarprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sarprasPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(btnAdd_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
            .addGroup(sarprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sarprasPanelLayout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(146, Short.MAX_VALUE)))
        );

        content.add(sarprasPanel, "card6");

        form_add_srp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Add Sarpras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel34.setText("Kode Sarana");

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel35.setText("Nama Sarana");

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel36.setText("Jumlah");

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel37.setText("Kondisi");

        txt_kondisi_sarpras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kondisi ....", "Bagus", "Rusak sedang", "Rusak Parah" }));

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel40.setText("Jenis");

        btnSimpanSrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanSrpMouseClicked(evt);
            }
        });
        btnSimpanSrp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText(" Simpan");
        btnSimpanSrp.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        btnSimpanSrp.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        txt_jenis_sarpras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis --", "Elektronik", "Non-Elektronik" }));

        javax.swing.GroupLayout form_add_srpLayout = new javax.swing.GroupLayout(form_add_srp);
        form_add_srp.setLayout(form_add_srpLayout);
        form_add_srpLayout.setHorizontalGroup(
            form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_add_srpLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel40))
                .addGap(38, 38, 38)
                .addGroup(form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_kdSarpras)
                    .addComponent(txt_nm_sarpras)
                    .addComponent(txt_jumlah_sarpras)
                    .addComponent(txt_kondisi_sarpras, 0, 163, Short.MAX_VALUE)
                    .addComponent(txt_jenis_sarpras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_add_srpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpanSrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        form_add_srpLayout.setVerticalGroup(
            form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_add_srpLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kdSarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txt_nm_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txt_jumlah_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txt_kondisi_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_add_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txt_jenis_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpanSrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_sarprasLayout = new javax.swing.GroupLayout(add_sarpras);
        add_sarpras.setLayout(add_sarprasLayout);
        add_sarprasLayout.setHorizontalGroup(
            add_sarprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_sarprasLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(form_add_srp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        add_sarprasLayout.setVerticalGroup(
            add_sarprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_sarprasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(form_add_srp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        content.add(add_sarpras, "card7");

        form_edit_srp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Sarpras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel41.setText("Kode Sarana");

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel42.setText("Nama Sarana");

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel43.setText("Jumlah");

        jLabel44.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel44.setText("Kondisi");

        kondisi_sarpras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kondisi ....", "Bagus ", "Rusak sedang", "Rusak Parah" }));

        jLabel45.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel45.setText("Jenis");

        btnEditSrp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditSrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditSrpMouseClicked(evt);
            }
        });
        btnEditSrp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Edit");
        btnEditSrp.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 30));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        btnEditSrp.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jenis_sarpras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis --", "Elektronik", "Non-Elektronik" }));

        btnHpsSrp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHpsSrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHpsSrpMouseClicked(evt);
            }
        });
        btnHpsSrp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Hapus");
        btnHpsSrp.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hapus.png"))); // NOI18N
        btnHpsSrp.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        javax.swing.GroupLayout form_edit_srpLayout = new javax.swing.GroupLayout(form_edit_srp);
        form_edit_srp.setLayout(form_edit_srpLayout);
        form_edit_srpLayout.setHorizontalGroup(
            form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_edit_srpLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45))
                .addGap(38, 38, 38)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kdSarpras)
                    .addComponent(nm_sarpras)
                    .addComponent(jumlah_sarpras)
                    .addComponent(kondisi_sarpras, 0, 163, Short.MAX_VALUE)
                    .addComponent(jenis_sarpras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(form_edit_srpLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnEditSrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHpsSrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        form_edit_srpLayout.setVerticalGroup(
            form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_edit_srpLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdSarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(nm_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jumlah_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(kondisi_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jenis_sarpras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(form_edit_srpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditSrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsSrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formEditSrpLayout = new javax.swing.GroupLayout(formEditSrp);
        formEditSrp.setLayout(formEditSrpLayout);
        formEditSrpLayout.setHorizontalGroup(
            formEditSrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEditSrpLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(form_edit_srp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        formEditSrpLayout.setVerticalGroup(
            formEditSrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEditSrpLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(form_edit_srp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        content.add(formEditSrp, "card8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(30,194,235));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(10,157,194));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnSarprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSarprasMouseEntered
        // TODO add your handling code here:
        btnSarpras.setBackground(new Color(30,194,235));
    }//GEN-LAST:event_btnSarprasMouseEntered

    private void btnSarprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSarprasMouseExited
        // TODO add your handling code here:
        btnSarpras.setBackground(new Color(10,157,194));
    }//GEN-LAST:event_btnSarprasMouseExited

    private void btnRuanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuanganMouseEntered
        // TODO add your handling code here:
        btnRuangan.setBackground(new Color(30,194,235));
    }//GEN-LAST:event_btnRuanganMouseEntered

    private void btnRuanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuanganMouseExited
        // TODO add your handling code here:
        btnRuangan.setBackground(new Color(10,157,194));
    }//GEN-LAST:event_btnRuanganMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setBackground(new Color(30,194,235));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        btnHome.setBackground(new Color(10,157,194));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnSarprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSarprasMouseClicked
        // TODO add your handling code here:
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(sarprasPanel);
        content.repaint();
        content.revalidate();
        table_sarpras();
    }//GEN-LAST:event_btnSarprasMouseClicked

    private void btnRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuanganMouseClicked
        // TODO add your handling code here:
        indexRuangan();
    }//GEN-LAST:event_btnRuanganMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(dashboarPanel);
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnAdd_sarprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_sarprasMouseClicked
        // TODO add your handling code here:
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(add_sarpras);
        content.repaint();
        content.revalidate();
        
    }//GEN-LAST:event_btnAdd_sarprasMouseClicked

    private void btnSimpanSrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanSrpMouseClicked
        // TODO add your handling code here:
       String kd = txt_kdSarpras.getText();
       String nm = txt_nm_sarpras.getText();
       String jumlah = txt_jumlah_sarpras.getText();
       int jmlh = Integer.parseInt(jumlah);
       Object kondisi = txt_kondisi_sarpras.getSelectedItem();
       Object jenis = txt_jenis_sarpras.getSelectedItem();
       
       Sarpras sr = new SarprasController();
       sr.Simpan(kd, nm, jmlh, kondisi, jenis);
       Clear();
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(sarprasPanel);
        content.repaint();
        content.revalidate();
        table_sarpras();
    }//GEN-LAST:event_btnSimpanSrpMouseClicked

    private void sarprasPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sarprasPanelComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sarprasPanelComponentShown

    private void tbl_sarprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sarprasMouseClicked
        // TODO add your handling code here:
        formSarpras();
    }//GEN-LAST:event_tbl_sarprasMouseClicked

    private void btnEditSrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditSrpMouseClicked
        // TODO add your handling code here:
        String kd = kdSarpras.getText();
        String nm = nm_sarpras.getText();
        String jumlah = jumlah_sarpras.getText();
        int jmlh = Integer.parseInt(jumlah);
        Object kondisi = kondisi_sarpras.getSelectedItem();
        Object jenis = jenis_sarpras.getSelectedItem();
        Sarpras sr = new SarprasController();
        sr.Edit(kd, nm, jmlh, kondisi, jenis);
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(sarprasPanel);
        content.repaint();
        content.revalidate();
        table_sarpras();
    }//GEN-LAST:event_btnEditSrpMouseClicked

    private void btnHpsSrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHpsSrpMouseClicked
        // TODO add your handling code here:
        String kd = kdSarpras.getText();
        Sarpras sr = new SarprasController();
        sr.Hapus(kd);
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(sarprasPanel);
        content.repaint();
        content.revalidate();
        table_sarpras();
    }//GEN-LAST:event_btnHpsSrpMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        content.add(formruangan);
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
       String kd = txt_kd.getText();
       String nm = txt_nama.getText();
       String jumlah = txt_jumlah.getText();
       int jmlh = Integer.parseInt(jumlah);
       Object kondisi = txt_kondisi.getSelectedItem();
       Ruangan rr = new RuanganController();
       rr.Simpan(kd, nm, jmlh, kondisi);
       indexRuangan();
       
       
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tbl_ruanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ruanganMouseClicked
        // TODO add your handling code here:
        formRuangan();
    }//GEN-LAST:event_tbl_ruanganMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
       String kd = kd_ruangan.getText();
       String nm = nm_ruangan.getText();
       String jum = jumlah.getText();
       int jmlh = Integer.parseInt(jum);
       Object kondisis = kondisi.getSelectedItem();
       Ruangan rr = new RuanganController();
       rr.Edit(kd, nm, jmlh, kondisis);
       indexRuangan();
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        String kd = kd_ruangan.getText();
        Ruangan rr = new RuanganController();
        rr.Hapus(kd);
        indexRuangan();
    }//GEN-LAST:event_btnHapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_sarpras;
    private javax.swing.JPanel btnAdd;
    private javax.swing.JPanel btnAdd_sarpras;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnEditSrp;
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnHpsSrp;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnRuangan;
    private javax.swing.JPanel btnSarpras;
    private javax.swing.JPanel btnSimpan;
    private javax.swing.JPanel btnSimpanSrp;
    private javax.swing.JPanel content;
    private javax.swing.JPanel dashboarPanel;
    private javax.swing.JPanel editHapusPanel;
    private javax.swing.JPanel formEditSrp;
    private javax.swing.JPanel form_add;
    private javax.swing.JPanel form_add_srp;
    private javax.swing.JPanel form_edit;
    private javax.swing.JPanel form_edit_srp;
    private javax.swing.JPanel formruangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jenis_sarpras;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlah_sarpras;
    private javax.swing.JTextField kdSarpras;
    private javax.swing.JTextField kd_ruangan;
    private javax.swing.JComboBox<String> kondisi;
    private javax.swing.JComboBox<String> kondisi_sarpras;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel navbar;
    private javax.swing.JTextField nm_ruangan;
    private javax.swing.JTextField nm_sarpras;
    private javax.swing.JPanel ruanganPanel;
    private javax.swing.JPanel sarprasPanel;
    private javax.swing.JLabel session;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tbl_ruangan;
    private javax.swing.JTable tbl_sarpras;
    private javax.swing.JComboBox<String> txt_jenis_sarpras;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_jumlah_sarpras;
    private javax.swing.JTextField txt_kd;
    private javax.swing.JTextField txt_kdSarpras;
    private javax.swing.JComboBox<String> txt_kondisi;
    private javax.swing.JComboBox<String> txt_kondisi_sarpras;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nm_sarpras;
    private javax.swing.JPanel welcomeText;
    // End of variables declaration//GEN-END:variables
}
